### ISSUE TITLE
Asterisk characters are not properly escaped in README.adoc

### ISSUE THREAD

**Issue by kiuxfr** [spring-guides/gs-handling-form-submission#21] opened 2019-10-28 15:06 UTC
in the text. But was not able to make a pull request.

2 asteriks are not properly escaped in the  text.

**Comment by robertmcnees** [comment] 2024-07-02 19:45
Hi @kiuxfr. I see what you mean. In the `README.adoc`:

```
The two form fields, expressed with `th:field="*{id}"` and
`th:field="*{content}"`, correspond to the fields in the `Greeting` object.
```

Which renders to:

> The two form fields, expressed with th:field="{id}" and th:field="{content}", correspond to the fields in the Greeting object.

Because of not escaping the *, the word **and** is bolded in our documentation. Another tip something isn't working.

I'm no expert in the matter, but played around and I think that escaping in this way should do the trick:

```
The two form fields, expressed with `th:field="+*+{id}"` and
`th:field="+*+{content}"`, correspond to the fields in the `Greeting` object.
```

Perhaps @Buzzardo has a better way. It isn't as simple as escaping with a `/`.

Seems like a good change for the community. I'll mark it as good for first time contributor. 

It's been a while since you opened this issue, but I do hope you try again to submit a PR. In addition to the link @Buzzardo provided, I usually link people to [this video](https://www.youtube.com/watch?v=kHZzQR9ntvc) by two Spring Engineers for an overview of the OSS process.

If anyone runs into problems submitting a PR let's continue the conversation.

**Comment by Aysha-py** [comment] 2024-07-04 02:33
Hi @robertmcnees, I will like toopen a PR for this issue. I see where the issue is in the documentation.

**Comment by Aysha-py** [comment] 2024-07-05 01:14
I created a Pr at #31 

However I noticed that there is a single asterik befor "{id}"and "{content}"as seen below

`th:field="*{id}" and th:field="*{content}"`

Is this correct?

Please take a look at this @Buzzardo @robertmcnees

**Comment by robertmcnees** [comment] 2024-07-08 17:20
Looks good! I can see that the live documentation now includes this fix. Closing this issue. Thanks for the PR.

**Closed by robertmcnees** 2024-07-08 17:20 UTC
Labels: bug, good first issue, help wanted
